### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by BernhardScharrer** [Gunpvp/Gunpvp#2]
@tomlangs 

![image](https://user-images.githubusercontent.com/17272798/28454486-c30bf034-6dfb-11e7-92ee-784070194cfc.png)

Bitte fix de NPE!

Se nervt mittlerweile schau ziemli!

(exististiert seit a paar tagen)

**Comment by tomlangs** [comment]
Fixed in commit
https://github.com/Gunpvp/Gunpvp/commit/416bef84a0c07b25f35c5a38bc7dcf09842c3ba0
